import Head from "next/head";
import Image from "next/image";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import styles from "../styles/about.module.css"

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Peniacc Digital Solutions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo3.png" />
                <meta charset="UTF-8"/>
                <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>        
            </Head>

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />

            <Navbar/>

            {/* SECTION 1 */}
            <div className={styles.about_us} id="about_us">
                <div className={styles.contents}>
                    <h1>WHO WE ARE</h1>
                </div>
            </div>

            {/* SECTION 2 */}
            <div className={styles.about} id="about">
                <div className={styles.content} id="content">
                    <div className={styles.left}>
                        <Image src="/assets/website.jpg" width={680} height={420} alt=""/>
                    </div>

                    <div className={styles.right}>
                        <div className={styles.text}>
                            A <span>Digital Marketing</span> Agency & an <span>IT</span> Solution Hub.
                        </div>

                        <p>We are those Guardians, who are positively restless and enjoy working by mutually helping people and companies reach their goals.
                        We are a creative digital agency delivering Integrated Marketing Communication & Information Technology services to help your business achieve its absolute brand potential.</p>
                        <br></br><p>Our expert team of design, development, digital, strategy and production specialist work to create, restore and evolve brand identity.
                        We collaborate with business houses who aspire to unlock the unique value of their brand.</p>
                        <br></br><p>We believe that what we do must have a real impact in the reality as well as in the convectional market place with a wide array of services ranging from <b>web & s/w development</b>, <b>digital marketing services</b>, <b>video production</b>,
                             <b>photography</b>, <b>Bulk messaging</b> or <b>branding</b> to <b>data infrastructure</b>; we do it all.</p>

                    </div>
                </div>
            </div>

            {/* SECTION 3- CTA */}
            <div className={styles.cta}>
            <h5>As an integrated Marketing Agency & IT solution Hub, we blend creativity and technology to provide the best possible outcomes to taking your business forward. </h5>
            <h6>imagine. create. grow</h6>
            </div>

            <Footer/>
        </div>
    );
}