import Head from "next/head";
import Image from "next/image";
import React, { useRef } from 'react';
import emailjs from '@emailjs/browser';
import styles from '../styles/contacts.module.css'
import Footer from "./components/footer";
import Navbar from "./components/navbar";


export default function Contacts() {

    const form = useRef();

    const sendEmail = (e) => {
      e.preventDefault();
  
      emailjs.sendForm
      ('service_cp1upkl', 
      'template_yw5gupo', 
      form.current, 
      'nhzdeWM1ScvpJVUqX')
        .then((result) => {
            console.log(result.text);
            console.log("Your message is sent")
        }, (error) => {
            console.log(error.text);
        });
    };

    return (
        <>
            <Head>
                <title>Peniacc Digital Solutions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo3.png" />
                <meta charset="UTF-8"/>
                <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>        
            </Head>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
            
            <Navbar/>
            <div className={styles.contacts}>
                <div className={styles.contents}>
                    <h2>GET IN TOUCH</h2>
                </div>
            </div>
            <div className={styles.contact}>
                <div className={styles.content}>
                    <p>Do you have any questions for us or need a quote?</p>
                </div>
                <div className={styles.container}>
                    <div className={styles.contactInfo}>
                        <div className={styles.box}>
                            <div className={styles.icon}><i class="fa fa-map-marker-alt" aria-hidden="true"></i></div>
                            <div className={styles.text}>
                                <h3>Address</h3>
                                <p>1st Floor, Chali Plaza</p>
                                <p>Ngong, Kenya</p>
                            </div>
                        </div> 
                        <div className={styles.box}>
                            <div className={styles.icon}><i class="fa-solid fa-phone"></i></div>
                            <div className={styles.text}>
                                <h3>Office Tel</h3>
                                <p>+254 713 265 002</p>
                            </div>
                        </div>
                        <div className={styles.box}>
                            <div className={styles.icon}><i class="fa-solid fa-envelope"></i>
                            </div>
                            <div className={styles.text}>
                                <h3>Email</h3>
                                <p>info@peniaccds.com</p>
                                
                            </div>
                        </div>
                    </div>
                    <div className={styles.contactForm}>
                        <form ref={form} onSubmit={sendEmail}>
                            <h2>Message Us</h2>
                            <div className={styles.inputBox}>
                                <input type="text" name="name" required="required" autocomplete="off"/>
                                <span>Full Name</span>
                            </div>
                            <div className={styles.inputBox}>
                                <input type="email" name="user_email" required="required" autocomplete="off"/>
                                <span>Email</span>
                            </div>
                            <div className={styles.inputBox}>
                                <input type="text" name="project" required="required" autocomplete="off"/>
                                <span>Project</span>
                            </div>
                            <div className={styles.inputBox}>
                                <textarea name="message" required="required"></textarea>
                                <span>Type your message...</span>
                            </div>
                            <div className={styles.inputBox}>
                                <input type="submit" name="" value="SEND"/>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <Footer/>

        </>
        
    );
}