import Head from "next/head";
import Image from "next/image";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import styles from "../styles/digi.module.css"
import Link from "next/link";

export default function Digimarketing(){
    return(
        <>
            <Head>
                <title>Peniacc Digital Solutions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo3.png" />
                <meta charset="UTF-8"/>
                <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>        
            </Head>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
             <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
           
            <Navbar/>
            <div className={styles.service} id="service">
                <div className={styles.contents}>
                    <h1>Digi Marketing</h1>
                </div>
                 
            </div>

            {/* SERVICE MAIN SECTION */}
            <div className={styles.newSec3}>
                <div className={styles.features1}></div>
                <div className={styles.innerSection1}>
                    <h6>01. </h6>
                    <div className={styles.text}><span>Branding</span></div>
                    <p>We make your brand vision a reality. Our unique ideas and concepts will help you build a distinct bond by branding your sales, generating higher client value, and increasing revenue opportunities. We help you identify and nurture the best
                        prospects. With your branding safe in our hands, you get to concentrate on more strategic requirements for your business.
                    </p>

                    <h4>Our Approach</h4>
                    <div className={styles.faq1}>
                        <div className={styles.text1}>&rarr; Discovery<span>(Competitive dissection, Illumination, Objectives, Analysis)</span></div>

                        <div className={styles.text1}>&rarr; Visual Identity<span>(Brand guidlines, Color palette, Font family, Logo creation)</span></div>

                        <div className={styles.text1}>&rarr; Personality<span>(Voice creation, Nomenclature, Brand ethos, Tagline)</span></div>


                    </div>
                    <Link href="/contacts">INTERESTED</Link>

                </div>

            </div>



            <div className={styles.newSec4}>

                <div className={styles.innerSection4}>
                    <h6>02.</h6>
                    <div className={styles.text4}><span>Videography</span></div>
                    <p>We specialise in making compelling corporate videos, explainer videos, promotional videos that promote sales and boost growth of an organisation.
                        If you want your event to be etched in the memory of guests even after the show day, what better way to do it than record it on camera and create an event video?
                    </p>
                    <p> Be it for promotion, branding or other purposes, videos can attract a range of customers to your brand and boost your sales and growth. Hosting an award ceremony or conference and looking out for a team to create professional videos?
                        Our team will breathe life into your videos and offer your viewers the ultimate visual experience.

                    </p>



                    <Link href="/contacts">INTERESTED</Link>


                </div>
                <div className={styles.features4}></div>

            </div>

            <div className={styles.newSec5}>
                <div className={styles.features5}></div>
                <div className={styles.innerSection5}>
                    <h6>03.</h6>
                    <div className={styles.text}><span>Photography</span></div>
                    <p>We are a Nairobi based photo studio and have been creating moving content for various mediums since few years now. Our team of skilled photographers have experience working for smaller brands, as well as established organizations. We work
                        keeping in mind the client&apos;s budget and more importantly the brief that is our paramount focus.
                    </p>

                    <h4>Our Approach</h4>
                    <div className={styles.faq5}>
                        <div className={styles.text5}>&rarr; People<span>(Candid, Events, Potraits, Headshots)</span></div>

                        <div className={styles.text5}>&rarr; Products<span>(Industrial, Hero shots, Social content, Product images)</span></div>

                        <div className={styles.text5}>&rarr; Lifestyle<span>(Food, Roadshows, Corporate shoots, Events & Seminars)</span></div>


                    </div>
                    <Link href="/contacts">INTERESTED</Link>

                </div>

            </div>


            <div className={styles.newSec6}>

                <div className={styles.innerSection6}>
                    <h6>04.</h6>
                    <div className={styles.text}><span>E-Commerce Optimization</span></div>
                    <p>We connect two worlds flawlessly, you and your audience. We specialize in <strong>Paid Ads</strong>, <strong>SEO Audit</strong>, <strong> ON Page SEO</strong>, <strong> OFF page SEO</strong>,<strong> E - Commerce SEO</strong>,
                        <strong>Content Management</strong>, <strong> Crisis Management</strong>, <strong>Social Ads</strong> ,<strong>influencer engagement</strong>,
                        <strong> Search Analysis</strong> and the list goes on.
                    </p>

                    <h4>Our Approach</h4>
                    <div className={styles.faq6}>
                        <div className={styles.text6}>&rarr; Social Media<span>(Marketing, Optimization, Analytics, User engagement )</span></div>

                        <div className={styles.text6}>&rarr; SEO<span>(On-Page SEO, Off- Page SEO, Website monitoring, Content development)</span></div>

                        <div className={styles.text6}>&rarr; E-mail<span>(Campaign planning, Template creation, A/B testing, Subscriber management)</span></div>
                        <div className={styles.text6}>&rarr; ORM<span>(Search reputation, Review handling, Listing, Brand reputation)</span></div>
                        <div className={styles.text6}>&rarr; SEM<span>(PPC Campaigns, Display Ads, Search Ads, Banner Ads)</span></div>



                    </div>
                    <Link href="/contacts">INTERESTED</Link>

                </div>
                <div className={styles.features6}></div>
            </div>

            <Footer/>
        </>
    );
}