import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Footer from "./components/footer";
import styles from '../styles/homer.module.css'
import Navbar from "./components/navbar";
import { useState } from "react";



export default function Homer() {
    const [selected, setSelected] = useState(null)
    const toggle = (i) => {
        if (selected === i){
            return setSelected(null)
        }

        setSelected(i)
    }

    return(
        <>
             <Head>
                <title>Peniacc Digital Solutions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo3.png" />
                
            </Head>
            <Navbar/>
            
            {/* SECTION 1 */}
            <div className={styles.containerInfo}>
                {/* <div className={styles.overlay}></div> */}
                <video src="../assets/videoBg.mp4" autoPlay loop muted className={styles.video}/>

                <div className={styles.content}>
                    <h1>ACCESS TO THE GLOBAL MARKET</h1>
                    <h2>HAS NEVER BEEN MADE THIS EASY.</h2>
                    <p className={styles.centerText}>We build in our clients&lsquo; <strong>imaginations</strong> to <strong>create</strong> identifiable brands.</p>
                   <p className={styles.centerText}> That&lsquo;s how we mutually <strong>grow</strong>.</p>
                </div>
            </div>
            {/* SECTION 2 */}
            <div className={styles.containerInfo2}>
                <div className={styles.grid}>
                    <Link href="/digimarketing" >                        
                        <div className={styles.card}>
                            {/* <span><i class='fas fa-arrow-alt-right'></i></span> */}
                            <h2>PENIACC</h2>
                            <h2> DIGITAL MARKETING</h2>
                            <div className={styles.wrapper}>
                                <div className={styles.anime}>
                                    {/* <p className={styles.statictxt}>...</p> */}
                                    <ul className={styles.dynamictxt}>
                                        <li><span>Branding</span></li>
                                        <li><span>SM Support</span></li>
                                        <li><span>Photography</span></li>
                                        <li><span>Videography</span></li>
                                        <li><span>PR Communication</span></li>
                                    </ul>
                                </div>
                            </div>
                            <p>&rarr;</p>
                        </div>                        
                    </Link>
                    <Link href="/tech_hub" >                        
                        <div className={styles.cardits}>
                            {/* <span><i class='fas fa-arrow-alt-right'></i></span> */}
                            <h2>PENIACC</h2>
                            <h2> TECHNOLOGY HUB</h2>
                            <div className={styles.animer}>
                                {/* <p className={styles.statictxt}>...</p> */}
                                <ul className={styles.dynamictxt}>
                                    <li><span>Web Applications</span></li>
                                    <li><span>Mobile Applications</span></li>
                                    <li><span>Firmware Development</span></li>
                                    <li><span>UI/UX Design</span></li>
                                    <li><span>Data Infrastructure</span></li>
                                </ul>
                            </div>
                            <p>&rarr;</p> 
                        </div>
                    </Link>
                </div>

                 <div className={styles.text}>
                    <p className={styles.txt1}>As an integrated Marketing Agency & IT Solutions Hub, we blend creativity and technology to provide the best possible outcomes to taking your business forward.</p>
                </div>
                <div className={styles.text1}>
                    <p className={styles.txt2}>We are those Guardians, who are positively restless and enjoy working by mutually helping people and companies reach their goals.</p>
                    </div>
            </div>

            {/* SECTION 3 */}
            <div className={styles.newSec1}>
                <div className={styles.features}></div>
                <div className={styles.innerSection}>
                    <h2 className={styles.titled}>WHY US</h2>                    
                    <div className="accordion">
                        {data.map((item, i) =>(
                            <div className='item' key={item.question}>
                                <div className={styles.title} onClick={() => toggle(i)} >
                                    <h4>{item.question}</h4>
                                    <span>{selected === i ? '-' : '+'}</span>
                                </div>
                                <div className={selected === i ? 'flair show' : 'flair'}>{item.answer}</div> 
                            </div>
                        ))}
                    </div>
                </div>

            </div>


            {/* SECTION 4 */}
            <div className={styles.newSec2}>
                <div className={styles.heading}>How we work </div>

                <div className={styles.teamContent}>
                    <div className={styles.left}>
                        <p>We are a creative digital agency delivering integrated marketing communication & Information Technology services to help your business achieve its absolute brand potential.</p>
                        <p>Our expert team of design, development, digital, strategy, and production specialist work to create, restore and evolve brand identity.</p><p> We collaborate with business houses who aspire to unlock the unique value of their brand.Our
                            approach ensures high quality turnout for every brief and success in every partnership we undertake.
                        </p>

                    </div>
                    
                    <div className={styles.right}>
                        <Image src="/assets/concepts.jpg" width={680} height={420} alt=""/>
                    </div>
                    

                </div>

                <div className={styles.img_wrapper}>
                    <Image src="/assets/problem-solving.png" alt="" width={1500} height={160}/>
                </div>



                <div className={styles.heading1}>Our Team </div>
                <div className={styles.teamContent1}>
                    
                    <div className={styles.left}>
                        <Image src="/assets/team.jpg" width={680} height={420} alt=""/>
                    </div>
                    
                    <div className={styles.right}>
                        <p>&quot;Talent wins games, but teamwork and intelligence win championships.&quot;</p> 
                        <p>We boast of creative & innovative minds that provide deep industry and market knowledge, impactful strategies, a breadth of public relations & communications expertise and a focus on innovation. We are constantly
                            evolving & looking for creative-unique ways to meet the demands our clients face in their businesses, and to drive deep meaningful impact by helping them communicate better with the public. </p><p>We are continually adding fresh talent and
                            looking for ways to hire differently and are committed to investing in our staff to ensure they are the best they can be.
                        </p>
                    </div>

                </div>

            </div>


            <Footer/>
        </>
    );
}
const data = [
    {
        question:'We will  Work Beyond The Project Scope',

        answer:' Ultimately, it comes down to dedication to a project. Doing great work means more to us than just a win for a brand. This helps us win thus creating new case studies which allows us win future business.',
    },
    {
        question:'We are Experts In Your Industry',
        answer:'We understand how to leverage the right marketing mix to amplify the mission driven work of change making organizations. All this while addressing the challenges and opportunities that come along with being a social enterprise.',
    },
    {
        question:'We are Perpetually Transforming To Meet Market Needs',
        answer:'Being a great agency partner requires a team with a perpetual transformation mindset. Innovation and how consumers make purchase decisions evolve by the minute. We invest in tomorrow and we have the scale to give our clients an advantage in their market.',
    },
    {
        question:'Are We The Right Fit For You?',
        answer:'We believe we are great at what we do with accolades, track record and case studies for support. But frankly, there are a lot of great agencies and even a great agency does not always sync with a client culture. This will let you to decide that we are not only the best agency, but also a great fit.',
    },

]

 