import Head from "next/head";
import Link from "next/link";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import styles from "../styles/tech.module.css"

export default function Tech_hub(){
    return(
        <>
            <Head>
                <title>Peniacc Digital Solutions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo3.png" />
                <meta charset="UTF-8"/>
                <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>        
            </Head>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
           
            <Navbar/>
            <div className={styles.service} id="service">
                <div className={styles.contents}>
                    <h1>Tech Hub</h1>
                </div>
                 {/* <h2><span>_</span> What We Do</h2> */}
            </div>

            <div className={styles.newSec7}>
                <div className={styles.features7}></div>
                <div className={styles.innerSection7}>
                    <h6>01.</h6>
                    <div className={styles.text}><span>Web Apps Development</span></div>
                    <p>We offer web development that replicate your company vision and improve visitor bounce rates on your website.</p><p> The designs are based on latest technology trends with the emphasis on Adaptive/Responsive design, cross-browser functionality,
                        industry standard page load speeds, optimisation, testing & validation, mobile-first web design, web app development, technical writing, knowledge-base development on web apps and W3C standard coding.
                    </p>

                    <h4>Our Approach</h4>
                    <div className={styles.faq7}>
                        <div className={styles.text7}>&rarr; Strategy<span>(Wireframes & Sitemaps, Exploration, Approach, UI)</span></div>

                        <div className={styles.text7}>&rarr; Design<span>(Adaptive design, Interactivity, Aesthetic, UI)</span></div>

                        <div className={styles.text7}>&rarr; Development<span>(Cross-browser compatibility, Device compatibility, Site realization, SEO ready)</span></div>

                    </div>
                    <Link href="/contacts">INTERESTED</Link>

                </div>

            </div>
            {/* service mobile apps */}

            <div className={styles.newSec4}>

                <div className={styles.innerSection4}>
                    <h6>02.</h6>
                    <div className={styles.text4}><span>Mobile Apps Development</span></div>
                    <p>We provide top-notch Android and iOS app development services powered through evolutionary architecture and innovations.</p><p> Our end-to-end solutions are highly customizable and cater to a wide range of business requirements.
                        So whether you need standalone, native, web-based, or database-driven applications, we deliver high-end mobile applications.
                    </p>
                    
                    <h4>Mobile Apps Dvt Services Range</h4>
                    <div className={styles.faq7}>
                        <div className={styles.text7}>&rarr; App UI/UX Design<span>(Responsive and interactive designs for higher conversions)</span></div>

                        <div className={styles.text7}>&rarr; Backend development<span>(Scalable, secure and robust backend architecture)</span></div>

                        <div className={styles.text7}>&rarr; QA & Support<span>(instant error resolution for your applications)</span></div>
                        <div className={styles.text7}>&rarr; Mobile Apps Evolution<span>(introduction of cutting-edge technologies that ensure expansion of your business operations)</span></div>

                    </div>
                    <Link href="/contacts">INTERESTED</Link>                   

                </div>
                <div className={styles.features4}></div>

            </div>
            {/* service firmware */}
            <div className={styles.newSec8}>
                <div className={styles.features8}></div>
                <div className={styles.innerSection8}>
                    <h6>03.</h6>
                    <div className={styles.text}><span>Firmware Development</span></div>
                    <p>We offer firmware development services for 8, 16, 32, and 64-bit microcontrollers. We design both bare-metal and RTOS-based firmware</p><p> We take care of low-level firmware development.</p><p> We engage with the redesign and debugging projects where you need to optimize the performance (latency, boot-time, power, and memory) of your existing firmware. We have extensive experience with hardware, operating systems, low-level diagnostic and performance tools. </p><p>We design firmware for multi-protocol and system-on-chip (SoC) devices which find their applications in industrial automation, healthcare, consumer electronics, and other industries.
                    </p>

                    <h4>Our Approach</h4>
                    <div className={styles.faq7}>
                        <div className={styles.text7}>&rarr; Requirements Analysis
                        </div>

                        <div className={styles.text7}>&rarr; Design and Algorithm Composing</div>

                        <div className={styles.text7}>&rarr; Firmware Coding</div>
                        <div className={styles.text7}>&rarr; System Testing</div>

                    </div>
                    <Link href="/contacts">INTERESTED</Link>

                </div>

            </div>

            {/* service uiux */}
            <div className={styles.newSec9}>

                <div className={styles.innerSection9}>
                    <h6>04.</h6>
                    <div className={styles.text4}><span>UI/UX Design</span></div>
                    <p>From the days of the screeching modem via the landline blocking every phone call, we have been connected. Designing websites, landing pages and understanding every piece of code has transcended our branding capabilities to the virtual world.</p><p> With expertise in design, user experiences and online behavior, we deliver your brand with digital relevance for today’s connected world.
                    We have evolved our design capabilities over the years with the deep understanding of online user behavior.</p><p> We create web and App interfaces that reflect the brand&lsquo;s aesthetic, while constantly evolving the user experience of the website or app to create a perfect balance of design and function.
                    </p>                   
                    <Link href="/contacts">INTERESTED</Link>


                </div>
                <div className={styles.features9}></div>

            </div>

            {/* service data Infrastructure */}
            <div className={styles.newSec10}>
                <div className={styles.features10}></div>
                <div className={styles.innerSection10}>
                    <h6>05.</h6>
                    <div className={styles.text}><span>Data Infrastructure</span></div>
                    <p>We install physical network infrastructure to connect devices and provide network connectivity within a company.
                    </p>

                    <h4>Our Approach</h4>
                    <div className={styles.faq7}>
                        <div className={styles.text7}>&rarr; Site Survey<span>(measurements, identifying pathways and routes, and evaluating existing infrastructure)</span></div>

                        <div className={styles.text7}>&rarr; Cable Selection & Installation<span>(bandwidth requirements, environmental factors consideration, mounting the cables, connection)</span></div>

                        <div className={styles.text7}>&rarr; Testing & Certification<span>(cable&lsquo;s & network performance, conducting continuity and resistance tests, and checking for potential crosstalk)</span></div>
                        <div className={styles.text7}>&rarr; Labeling & Documentation<span>(comprehensive network diagram, labeling cables for easy identification)</span></div>

                    </div>
                    <Link href="/contacts">INTERESTED</Link>

                </div>

            </div>

            <Footer/>
        </>
    );
}